[package]
name = "hf3fs-proto"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
hf3fs-types = { workspace = true }
hf3fs-serde = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
