[package]
name = "hf3fs-trash-cleaner"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
hf3fs-types.workspace = true
tokio.workspace = true
tracing.workspace = true
