[package]
name = "hf3fs-stubs"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
hf3fs-types.workspace = true
hf3fs-proto.workspace = true
async-trait.workspace = true
parking_lot.workspace = true

[dev-dependencies]
tokio.workspace = true
