[package]
name = "hf3fs-meta-server"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
hf3fs-types.workspace = true
hf3fs-meta-service.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
