[package]
name = "hf3fs-monitor-collector"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
hf3fs-types.workspace = true
hf3fs-monitor.workspace = true
tokio.workspace = true
tracing.workspace = true
