[package]
name = "hf3fs-fdb"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[features]
fdb = []

[dependencies]
hf3fs-types.workspace = true
hf3fs-kv.workspace = true
async-trait.workspace = true
