[package]
name = "hf3fs-fuse-mount"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
hf3fs-types.workspace = true
hf3fs-fuse.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
